version: 0.2

phases:
  install:
    commands:
      - echo install started on `date`
      - npm install -g @angular/cli 
  pre_build:
    commands:
      - echo pre-build started on `date`
      - npm install -g
  build:
    commands:
      - echo Build started on `date`
      - ng build
  post_build:
    commands:
      - echo post-build completed on `date`
      - aws s3 sync dist/ "s3://http://app.tbd-app.s3-website-us-east-1.amazonaws.com"
artifacts:
  base-directory: dist