version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - npm install -g
  build:
    commands:
      - echo Build started on `date`
      - ng build
  post_build:
    commands:
      - echo Build completed on `date`
      - aws s3 sync dist/ "s3://http://app.tbd-app.s3-website-us-east-1.amazonaws.com"
artifacts:
  base-directory: dist